### ISSUE TITLE
There is no DocumentIdBuilder

### ISSUE THREAD

**Issue by heitorfm** [gigya/flume-ng-elasticsearch-ser-ex#1]
The class ExtendedElasticSearchIndexRequestBuilderFactory is using the class org.apache.flume.sink.elasticsearch.DocumentIdBuilder. But this DocumentIdBuilder seems to be part of flume 1.3.1 but not 1.5.2

**Comment by rore** [comment]
Sorry, I still need to update the documentation here. 
This project is based on our own fork of Flume 1.5.2 - 
https://github.com/gigya/flume/tree/flume-1.5-es-sink-change

The Elasticsearch sink in Flume was changed and DocumentIdBuilder was added to be able to set the document ID when using the HTTP mode in the sink. It was not possible to do without changing the sink.

**Comment by heitorfm** [comment]
Now. It make sense :)
Thanks !
