### ISSUE TITLE
Error while compiling source code

### ISSUE THREAD

**Issue by amjadshabani** [gigya/flume-ng-elasticsearch-ser-ex#2]
Hello @rore 

I ve tried to compile the source code using maven:
`$ mvn clean install -DskipTests`
but I m always getting the error of 

`/home/amjad_alshabani/git/flume-ng-elasticsearch-ser-ex/src/main/java/com/gigya/flume/ExtendedElasticSearchLogStashEventSerializer.java:[87,99] error: cannot find symbol
[ERROR]  class DocumentIdBuilder`

I couldn't state the package that contains the class/Interface:
`org.apache.flume.sink.elasticsearch.DocumentIdBuilder`

Would you please tell me how i could get the code built?

**Comment by rore** [comment]
Yes, this project is based on our own fork of Flume 1.5.2 - 
https://github.com/gigya/flume/tree/flume-1.5-es-sink-change

The Elasticsearch sink in Flume was changed and DocumentIdBuilder was added to be able to set the document ID when using the HTTP mode in the sink. It was not possible to do without changing the sink.

**Comment by amjadshabani** [comment]
Thanx for the reply.

I ll try to adapt your changes in my release of Flume.
